# 2018-12-23 (cc) <paul4hough@gmail.com>
#
---
- name: create {{ remed_user }} user
  become: true
  user:
    name: "{{ remed_user }}"
    home: "{{ remed_dir }}"
    system: true

- name: create {{ remed_dir }} directories
  become: true
  become_user: "{{ remed_user }}"
  file:
    name: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ remed_dir }}/bin"
    - "{{ remed_dir }}/config"
    - "{{ remed_dir }}/data"

- name: upload maul binary
  become: true
  become_user: "{{ remed_user }}"
  copy:
    src: maul
    dest: "{{ remed_dir }}/bin/maul"
    mode: 0775

- name: install maul service file
  become: true
  template:
    src: systemd/maul.service.j2
    dest: /etc/systemd/system/maul.service

- name: enable and start maul service
  become: true
  systemd:
    name: maul
    state: started
    enabled: true
    daemon_reload: true
