# 2018-12-23 (cc) <paul4hough@gmail.com>
#
---
- name: create {{ mon_user }} user
  become: true
  user:
    name: "{{ mon_user }}"
    home: "{{ mon_dir }}"
    system: true

- name: create {{ mon_dir }} directories
  become: true
  become_user: "{{ mon_user }}"
  file:
    name: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ mon_dir }}/bin"
    - "{{ mon_dir }}/config"
    - "{{ mon_dir }}/data"

- name: upload monitor base binaries
  become: true
  become_user: "{{ mon_user }}"
  copy:
    src: "{{ lookup('env','GOPATH') + '/bin/' + item }}"
    dest: "{{ mon_dir }}/bin/{{ item }}"
    mode: 0775
  loop: "{{ mon_base_apps }}"

- name: install monitor services files
  become: true
  template:
    src: systemd/{{ item }}.service.j2
    dest: /etc/systemd/system/{{ item }}.service
  loop: "{{ mon_base_apps }}"

- name: enable and start monitor services
  become: true
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop: "{{ mon_base_apps }}"
