# 2018-12-23 (cc) <paul4hough@gmail.com>
#
---
- name: create {{ remed_dir }} directories
  become: true
  become_user: "{{ remed_user }}"
  file:
    name: "{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - "{{ remed_dir }}"
    - "{{ remed_dir }}/bin"
    - "{{ remed_dir }}/config"
    - "{{ remed_dir }}/playbooks"
    - "{{ remed_dir }}/scripts"

- name: install ansible
  become: true
  package:
    name: ansible
    state: present

- name: upload agate binary
  become: true
  become_user: "{{ remed_user }}"
  copy:
    src: agate
    dest: "{{ remed_dir }}/bin/agate"
    mode: 0775

- name: upload scripts
  become: true
  become_user: "{{ remed_user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ remed_dir }}/scripts"
    mode: 0775
  with_items:
    - scripts/remed-test-script

- name: upload playbooks
  become: true
  become_user: "{{ remed_user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ remed_dir }}/playbooks"
    mode: 0664
  with_fileglob:
    - playbooks/*.yml

- name: install agate service file
  become: true
  template:
    src: systemd/agate.service.j2
    dest: /etc/systemd/system/agate.service

- name: enable and start agate service
  become: true
  systemd:
    name: agate
    state: started
    enabled: true
    daemon_reload: true
