# 2018-12-23 (cc) <paul4hough@gmail.com>
#
---
- name: upload pg exporter grant sql
  template:
    src: pgsql-mon-grant.sql.j2
    dest: /tmp/pgsql-mon-grant.sql

- name: execute pg exporter grant sql
  become: true
  become_user: "postgres"
  shell: >-
    /usr/bin/psql
    < /tmp/pgsql-mon-grant.sql
    > /var/lib/pgsql/.pg_exp_grant
  args:
    creates: "/var/lib/pgsql/.pg_exp_grant"


- name: delete pg exporter grant sql
  file:
    path: /tmp/pgsql-mon-grant.sql
    state: absent

- name: install posgresql exporter
  become: true
  become_user: "{{ mon_user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ mon_dir }}/bin/{{ item }}"
    mode: 0775
  with_items:
    - postgres_exporter

- name: install exporter service file
  become: true
  template:
    src: systemd/{{ item }}.j2
    dest: /etc/systemd/system/{{ item }}
  with_items:
    - postgres_exporter.service

- name: enable and start postgres exporter services
  become: true
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  with_items:
    - postgres_exporter
