# 2018-12-23 (cc) <paul4hough@gmail.com>
# base tasks
---

- name: add my public key
  authorized_key:
    state: present
    user: "{{ ansible_user_id }}"
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: update RedHat family packages
  become: true
  yum:
    update_cache: true
    name: "*"
    state: latest
  when: ansible_os_family == 'RedHat'
